srnj01-cv05
nvbach91/4IZ278-2023-2024-LS pull request #114
Opened 2024-03-21 22:48 UTC by jakubsrnka

2024-03-21 23:18 UTC, jakubsrnka commented
odkaz na úkol: [https://eso.vse.cz/~srnj01/cv05/](https://eso.vse.cz/~srnj01/cv05/)

2024-03-22 09:21 UTC, nvbach91 requested changes

2024-03-22 09:21 UTC, nvbach91 commented on www/srnj01/cv05/database.php
> +    $pdo = DatabaseConnection::getPDOConnection();
tohle nebude fungovat, $pdo nebude dostupne v instancich podrazenych trid

2024-04-04 10:26 UTC, nvbach91 approved these changes

2024-04-04 10:26 UTC, merged