adad05-cv06
nvbach91/4IZ278-2023-2024-LS pull request #118
Opened 2024-04-04 12:19 UTC by danieladam2001

Dobrý den, odevzdávám domácí úkol 6.
Zde je odkaz na eso: https://eso.vse.cz/~adad05/cv06/

2024-04-04 22:47 UTC, nvbach91 requested changes

2024-04-04 22:47 UTC, nvbach91 commented on www/adad05/cv06/components/SlideDisplay.php
> +    <div class="carousel-item active"><img class="d-block img-fluid" src="<?php echo $slides[0]['img']; ?>" alt="<?php echo $slides[0]['title']; ?>" /></div>
tohle si nezaslouzi foreach?

2024-04-10 21:41 UTC, danieladam2001 commented on www/adad05/cv06/components/SlideDisplay.php
> +    <div class="carousel-item active"><img class="d-block img-fluid" src="<?php echo $slides[0]['img']; ?>" alt="<?php echo $slides[0]['title']; ?>" /></div>
Dobrý večer, pokusil jsem se opravit.

2024-04-18 21:29 UTC, nvbach91 approved these changes

2024-04-18 21:29 UTC, merged