adad05-cv08
nvbach91/4IZ278-2023-2024-LS pull request #137
Opened 2024-04-18 18:21 UTC by danieladam2001

Dobrý večer, odevzdávám úkol ze cv08.
Zde je link na eso: https://eso.vse.cz/~adad05/cv08/

2024-04-18 22:01 UTC, nvbach91 requested changes

2024-04-18 22:01 UTC, nvbach91 commented on www/adad05/cv08/edit-item.php
> +        <input type="text" name="name" value="<?php echo isset($name) ? $name : '' ?>"><br>
pokud jde o edit tak je dobry predvyplnit informace o zaznamu, data o editovanem zaznamu dostanete z databaze

2024-04-24 21:35 UTC, danieladam2001 commented on www/adad05/cv08/edit-item.php
> +        <input type="text" name="name" value="<?php echo isset($name) ? $name : '' ?>"><br>
Dobrý večer,

nahrál jsem commit. Nyní se u editu předvyplní původní data.
ID se ukazuje jako pole, ale měnit jsem nastavoval, že nelze.

Děkuji. S pozdravem
Daniel Adam

2024-04-25 21:19 UTC, nvbach91 approved these changes

2024-04-25 21:19 UTC, merged