srnj01-cv08
nvbach91/4IZ278-2023-2024-LS pull request #142
Opened 2024-04-18 21:54 UTC by jakubsrnka

2024-04-18 21:58 UTC, jakubsrnka commented
[https://eso.vse.cz/~srnj01/cv08/index.php](https://eso.vse.cz/~srnj01/cv08/index.php)

2024-04-18 22:16 UTC, nvbach91 requested changes

2024-04-18 22:16 UTC, nvbach91 commented on www/srnj01/cv08/cart.php
> +      echo '<h1 class="my-4">Your cart is empty!</h1>
HTML nedavame do echo, pouzivejte tohle
```php
<?php if (condition1): ?>
  <h1>...</h1>
<?php elseif (condition2): ?>
  <h2>...</h2>
<?php else: ?>
  <h3>...</h3>
<?php endif; ?>

2024-04-18 22:16 UTC, nvbach91 commented on www/srnj01/cv08/cart.php
> +        echo '<tr>
to same tady foreach + endforeach ...

a na dalsich mistech

2024-04-19 21:05 UTC, nvbach91 approved these changes

2024-04-19 21:06 UTC, merged