poij00-sp
nvbach91/4IZ278-2023-2024-LS pull request #191
Opened 2024-05-12 13:14 UTC by jirkapo

Vytvořeno připojení k databázi a další třídy týkající se databáze, zobrazení produktů, filtr na kategorie produktů,registrace, přihlašování, odhlašování.

2024-06-12 21:25 UTC, nvbach91 requested changes
- jak se dostanu do administrace?
- s testovanim aplikaci jsem skoncil brzo jelikoz neslo se prihlasit abych mohl odeslat objednavku

2024-06-12 21:25 UTC, nvbach91 commented on components/handleLogin.php
> +        $users->loginUser($username, $password);
![image](https://github.com/nvbach91/4IZ278-2023-2024-LS/assets/20724910/dd1fba9c-e63d-4b09-a3bd-f727d71184aa)

aplikace asi nebyla testovana na produkci

2024-06-12 21:25 UTC, nvbach91 commented on database/UsersDB.php
> +    $users = new UsersDB();
v tomhle soubory by mela byt jenom definice tridy, ne jeji instance

2024-06-12 21:25 UTC, nvbach91 commented on main/addProduct.php
> +            echo "<div class='registration-success' style='text-align: center;'>";
nedavame HTML do echo

2024-06-13 08:10 UTC, jirkapo commented on components/handleLogin.php
> +        $users->loginUser($username, $password);
Dobrý den, admin údaje: admin, pwd: Heslo.123 . Pro obyčejného uživatele se stačí zaregistrovat a přihlásit.

2024-06-14 11:13 UTC, nvbach91 commented
- po potvrzeni objednavky presmerovat do stranky prehledu objednavek
- stranka pro admina aby videl vsechny objednavky vsech uzivatelu a spravovat status
- zakazat pristup na editacni stranky uzivatelum kteri nejsou admin

2024-06-14 13:26 UTC, closed without merging