auza00-sp
nvbach91/4IZ278-2023-2024-LS pull request #199
Opened 2024-05-12 19:58 UTC by auzkya

First commit
- Neresponzivní grafika
- Přidávání a mazání spotu
- Like/unlike spot
- Přidání komentáře

2024-06-05 19:05 UTC, nvbach91 commented
Prace neni odevzdana

2024-06-05 20:27 UTC, nvbach91 requested changes
missing app URL

2024-06-05 20:46 UTC, auzkya commented
Dobrý večer,
moc se omlouvám, z nějakého důvodu jsem měl zafixováno, že projekt stačí odevzdat do půlnoci před obhajobou.
Na dodělaní projektu intenzivně pracuji, každopádně ještě mi bohužel zbývá přihlášení přes Facebook, stránka pro Admina (na mazání jakéhokoliv spotu) a pročistit kód.
Odkaz na samotný web: https://iknowaspot.eu/

2024-06-07 09:03 UTC, nvbach91 requested changes
- databazove rozhrani (OOP class pro kazdou tabulku) aspon pro uzivatele
- REST API
  - endpoint: GET /api/v1/spots?category=1 JSON
  - endpoint: GET /api/v1/comments?spot_id=15 JSON
- stranka seznam spotu /spots.php administrator only
- Cross site scripting `<script>` to text
- nerefreshovat stranku po pridavani komentare

2024-06-14 09:04 UTC, nvbach91 commented
- PULL REQUEST
- delete spot
- htmlspecialchars
- samostatny soubor pro konfiguracni udaje pro pripojeni do databaze

2024-06-14 12:42 UTC, closed without merging