kouv13-sp
nvbach91/4IZ278-2023-2024-LS pull request #213
Opened 2024-06-11 00:31 UTC by kouv13

verze bezici na lokalnim serveru pred upravou na server skolni

2024-06-12 20:37 UTC, nvbach91 commented
https://eso.vse.cz/~kouv13/sem

2024-06-12 21:06 UTC, nvbach91 requested changes
- jak se dostanu do administrace?

2024-06-12 21:06 UTC, nvbach91 commented on www/kouv13/sp/sem/signup/index.php
> +<body>
proc tady a na jinych strankach neni navigace?

2024-06-12 21:06 UTC, nvbach91 commented on kouv13/sp/sem/signup/addUser.php
> +    $password = htmlspecialchars($_POST["password"]);
chybi kontrola slozitosti hesla

2024-06-12 21:06 UTC, nvbach91 commented on www/kouv13/sp/sem/includes/reservation/reservation.class.php
> +                                                                        echo ' bg-dark full ';
a to neplati pro ranni hodiny kdyz ted uz je vecer?

2024-06-12 21:06 UTC, nvbach91 commented on www/kouv13/sp/sem/includes/reservation/reservation.class.php
> +class reservation
takhle se nepojmenovavaji tridy v PHP

2024-06-12 21:06 UTC, nvbach91 commented on www/kouv13/sp/sem/includes/reservation/confirmReservation.php
> +session_start();
bug?

![image](https://github.com/nvbach91/4IZ278-2023-2024-LS/assets/20724910/f82e3aae-6b5d-4580-906d-a3e233ded10a)

2024-06-12 21:06 UTC, nvbach91 commented on www/kouv13/sp/sem/includes/reservation/reservation.class.php
> +                                                if ($todayNumber == $n && $today >= $weekRange["m"] && $today <= $weekRange["s"]) {
lepsi formatovani kodu, a HTML nedavame do echo

2024-06-12 21:06 UTC, nvbach91 commented on www/kouv13/sp/sem/js/app.js
> +    var xmlhttp = new XMLHttpRequest();
tuhle aplikaci jste psal snad v roce 2000

2024-06-13 09:46 UTC, kouv13 commented
> * jak se dostanu do administrace?
> * co se stane s historickymi rezervacemi? take se zobrazuji prehledu rezervaci?

e: admin@mojehala.cz
h: heslo

2024-06-13 09:47 UTC, kouv13 commented
Opravy mám udělat do obhajoby nebo během obhajoby? Předem děkuji za odpověď.

2024-06-13 09:57 UTC, nvbach91 commented
Nejlepe pred, ale je to na Vas, hlavne ale opravte strukturu slozek v Pull Requestu - smazat duplicitni soubory a slozky

2024-06-13 10:07 UTC, nvbach91 commented
- upload obrazku nefunguje, pravdepodobne nemate nastaveno directory permission
- podle me jmeno sportu by melo byt unikatni
- co se stane s rezervacemi pokud se odstrani jejich hala?
- poslednich 15 rezervaci asi nestaci, pridejte strankovani a umoznit prohlizeni vsech rezervaci pomoci strankovani

2024-06-14 09:56 UTC, nvbach91 commented
- v pripade selhani requestu do formulare vypsat odeslane hodnoty.
- administrator muze rusit rezervace.
- OOP chybi
- oauth?

2024-06-14 12:40 UTC, closed without merging