srnj01-cv02
nvbach91/4IZ278-2023-2024-LS pull request #35
Opened 2024-02-23 14:38 UTC by jakubsrnka

odkaz na úkol:
[https://eso.vse.cz/~srnj01/cv02/](https://eso.vse.cz/~srnj01/cv02/)

2024-02-29 20:56 UTC, nvbach91 requested changes

2024-02-29 20:56 UTC, nvbach91 commented on www/srnj01/cv02/classes/Person.php
> +    return getFullName($this->firstName, $this->lastName);
tohle je matouci, stejny nazev funkce a metody, proc musite mit na tohle specialni funkci?

2024-03-07 20:42 UTC, jakubsrnka commented on www/srnj01/cv02/classes/Person.php
> +    return getFullName($this->firstName, $this->lastName);
odstraněno (externí metoda), teď vrací třída rovnou string, který sestavuje ze svých proměnných

2024-03-12 21:44 UTC, nvbach91 approved these changes

2024-03-12 21:44 UTC, merged