boxd00-cv02
nvbach91/4IZ278-2023-2024-LS pull request #42
Opened 2024-02-27 21:01 UTC by boxandav

Odevzdávám cvičení 2
https://eso.vse.cz/~boxd00/cv02

2024-02-29 21:11 UTC, nvbach91 requested changes

2024-02-29 21:11 UTC, nvbach91 commented on www/boxd00/cv02/utils/utils.php
> +function getAge($person) {
tyhle funkce implementovat jako metody tridy Person

2024-03-04 14:16 UTC, boxandav commented
Nahrávám novou verzi s opravou

2024-03-04 14:51 UTC, nvbach91 approved these changes

2024-03-04 14:51 UTC, merged