fanm02-cv03
nvbach91/4IZ278-2023-2024-LS pull request #60
Opened 2024-03-03 20:23 UTC by martin1080p

https://eso.vse.cz/~fanm02/cv03/index.php

2024-03-07 20:50 UTC, nvbach91 requested changes

2024-03-07 20:50 UTC, nvbach91 commented on www/fanm02/cv03/index.php
> +    $name = $_POST['name'];
htmlspecialchars, trim, ...

2024-03-07 20:50 UTC, nvbach91 commented on www/fanm02/cv03/index.php
> +    if (empty($email) || !filter_var($email, FILTER_VALIDATE_EMAIL)) {
filter_var uz kontroluje i prazdne hodnoty

2024-03-07 20:50 UTC, nvbach91 commented on www/fanm02/cv03/styles/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');
font se dava lepe do HTMl

2024-03-08 10:16 UTC, martin1080p commented on www/fanm02/cv03/index.php
> +    if (empty($email) || !filter_var($email, FILTER_VALIDATE_EMAIL)) {
opraveno

2024-03-08 10:16 UTC, martin1080p commented on www/fanm02/cv03/index.php
> +    $name = $_POST['name'];
opraveno

2024-03-12 21:46 UTC, nvbach91 approved these changes

2024-03-12 21:46 UTC, merged