boxd00-cv03
nvbach91/4IZ278-2023-2024-LS pull request #61
Opened 2024-03-05 10:13 UTC by boxandav

Odevzdávám cvičení 3
https://eso.vse.cz/~boxd00/cv03

2024-03-07 20:52 UTC, nvbach91 requested changes

2024-03-07 20:52 UTC, nvbach91 commented on www/boxd00/cv03/index.php
> +    $name = $_POST["name"];
htmlspecialchars, trim, ...

2024-03-07 20:52 UTC, nvbach91 commented on www/boxd00/cv03/index.php
> +    if (empty($email) || !preg_match("/\w+@\w+\.\w+/", $email)) {
prazdnou hodnotu uz resi vas regularni vyraz

2024-03-08 11:28 UTC, boxandav commented
Aktualizace cv03

2024-03-12 21:46 UTC, nvbach91 approved these changes

2024-03-12 21:46 UTC, merged