srnj01-cv03
nvbach91/4IZ278-2023-2024-LS pull request #73
Opened 2024-03-07 20:31 UTC by jakubsrnka

2024-03-07 20:32 UTC, jakubsrnka commented
https://eso.vse.cz/~srnj01/cv03/

2024-03-07 21:10 UTC, nvbach91 requested changes

2024-03-07 21:10 UTC, nvbach91 commented on www/srnj01/cv03/index.php
> +  $name = htmlspecialchars($_POST['name']);
jeste trim

2024-03-07 21:10 UTC, nvbach91 commented on www/srnj01/cv03/index.php
> +    $errors['phone'] = "Phone has to be at least 9 characters long";
obsah formulare neodpovida rozsahu zadani

2024-03-07 22:45 UTC, jakubsrnka commented on www/srnj01/cv03/index.php
> +    $errors['phone'] = "Phone has to be at least 9 characters long";
moje chyba, špatně jsem si přečetl zadání

2024-03-07 22:46 UTC, jakubsrnka commented on www/srnj01/cv03/index.php
> +  $name = htmlspecialchars($_POST['name']);
done

2024-03-12 21:50 UTC, nvbach91 approved these changes

2024-03-12 21:50 UTC, merged